backend:
  name: github
  repo: juanda99/web-aeducar

locale: 'es'
media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow

collections:
  - name: "faq" # Used in routes, e.g., /admin/collections/blog
    label: "faq" # Used in the UI
    folder: "src/faq" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de publicación", name: "date", widget: "datetime" }
      - {
          label: "URL",
          name: "slug",
          widget: "string",
          default: "/faq/nombre-faq",
        }
      - { label: "Texto faq", name: "body", widget: "markdown" }
